server:
  error:
    include-exception: true # 오류 응답에 exception 내용을 포함할지 여부
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할지 여부

  servlet:
    encoding:
      force: true


spring:
  h2:
    console:
      enabled: true

  sql:
    init:
      encoding: UTF-8

  datasources:
    url: jdbc:h2:mem:testdb

  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 20MB

uploadfile.dir: ./image/